### ISSUE TITLE
test

### ISSUE THREAD

**Issue by alefattorini** [nethesis/nethserver-openssh#3]
test

**Comment by DavidePrincipi** [comment]
Prova app *GitHub*

**Comment by alefattorini** [comment]
Prova arrivata

Inviato da Blue Mail



Il giorno 5 feb 2015 21:00, alle ore 21:00, Davide Principi <notifications@github.com> ha scritto:

**Comment by DavidePrincipi** [comment]
beautiful:
https://waffle.io/nethesis/nethserver-release

https://github.com/waffleio/waffle.io/wiki/FAQs#multirepo

**Comment by alefattorini** [comment]
Pronti? :-D

On 24/02/2015 16:15, Davide Principi wrote:
> beautiful:
> https://waffle.io/nethesis/nethserver-release
>
> https://github.com/waffleio/waffle.io/wiki/FAQs#multirepo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nethesis/nethserver-openssh/issues/3#issuecomment-75774720>.
>

-- 
Alessio Fattorini
Nethesis srl - Pesaro (Italy)
